### ISSUE TITLE
`Vue` as a constructor does not work (use-case: to provide a global Vuex store)

### ISSUE THREAD

**Issue by faceyspacey** [SmallComfort/react-vue#6]
The following doesn't work:

*vue.config.js:*
```js
import Vue from 'react-vue'
import Vuex from 'vuex'
import store from './src/store'
import App from './src/components/App'

Vue.use(Vuex)

export default new Vue({
  store,
  render: h => h(App)
})
```

because `Vue` isn't a constructor. What's the recommended way to use a global store?

here's the trace:

```
TypeError: Vue is not a constructor
    at Example.buildVM (/Users/jamesgillmore/React/universal-demo/node_modules/react-vue-helper/build.js:2751:16)
    at Example.componentWillMount (/Users/jamesgillmore/React/universal-demo/node_modules/react-vue-helper/build.js:2772:22)
    at Example.target.(anonymous function) [as componentWillMount] (/Users/jamesgillmore/React/universal-demo/node_modules/react-vue/build.js:4023:10)
    at /Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:348:23
    at measureLifeCyclePerf (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:347:9)
    at ReactCompositeComponentWrapper.mountComponent (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.mountChildren (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent._createContentMarkup (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
    at ReactDOMComponent.mountComponent (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactDOMComponent.js:520:29)
    at Object.mountComponent (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/jamesgillmore/React/universal-demo/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
```

**Comment by faceyspacey** [comment]
even if this didn't work as a constructor. u need somewhere to pass the store. if it was possible to pass just the `store` option, that would solve the use case. Obviously the `el` and `render` options may not matter in this react setup.

**Comment by faceyspacey** [comment]
i solved it with this:
```js
const VuexPlugin = {
  install(Vue) {
    Vue.prototype.$store = createStore()
  }
}

Vue.use(VuexPlugin)
```
> now you can use `mapGetters`, `mapActions`, etc, in your components :)

hopefully having these Issues here will help someone else.

...by the way, I'm primarily a React developer, so I'm figuring this out on the fly.
